//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalRetailersInc.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class digitalretailersincEntities : DbContext
    {
        public digitalretailersincEntities()
            : base("name=digitalretailersincEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<cart_status> cart_status { get; set; }
        public virtual DbSet<laptop> laptops { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<member_role> member_role { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<shipping_details> shipping_details { get; set; }
        public virtual DbSet<slide_image> slide_image { get; set; }
    }
}
