//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalRetailersInc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class slide_image
    {
        public int slide_id { get; set; }
        public string slide_title { get; set; }
        public string slide_image1 { get; set; }
    }
}
